# version: '3'

# services:

#   laravel_app:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile.apache
#     container_name: laravel_app_apache
#     volumes:
#       - ./backend:/var/www
#     ports:
#       - "8080:80"
#     environment:
#       DB_CONNECTION: mysql
#       DB_HOST: mysql_db
#       DB_PORT: 3306
#       DB_DATABASE: mydb
#       DB_USERNAME: user
#       DB_PASSWORD: secret

#   mysql_db:
#     image: mysql:8.0.31
#     container_name: mysql_db_apache
#     environment:
#       MYSQL_DATABASE: mydb
#       MYSQL_USER: user
#       MYSQL_PASSWORD: secret
#       MYSQL_ROOT_PASSWORD: secret
#     volumes:
#       - mysql_data:/var/lib/mysql
#     ports:
#       - "33060:3306"

# volumes:
#   mysql_data:

# react_app:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     container_name: react_app
#     volumes:
#       - ./frontend:/app
#     ports:
#       - "3000:3000"

version: '3'

services:
  react_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  laravel_app:
    build:
      context: ./backend
      dockerfile: Dockerfile.apache
    container_name: laravel_app_apache
    volumes:
      - ./backend:/var/www
    ports:
      - "8080:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_DATABASE: mydb
      DB_USERNAME: user
      DB_PASSWORD: secret

  mysql_db:
    image: mysql:8.0.31
    container_name: mysql_db_apache
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "33060:3306"

volumes:
  mysql_data: