version: '3'

services:

  laravel_app:
    build:
      context: ./backend
      dockerfile: Dockerfile.nginx
    container_name: laravel_app_nginx
    volumes:
      - ./backend:/var/www
    ports:
      - "8081:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_DATABASE: mydb
      DB_USERNAME: user
      DB_PASSWORD: secret

  mysql_db:
    image: mysql:8.0.31
    container_name: mysql_db_nginx
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "33061:3306"

volumes:
  mysql_data:

react_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"