jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and run Docker containers with Apache
      if: env.USE_APACHE == 'true'
      run: |
        docker-compose -f docker-compose.apache.yml up --build -d

    - name: Build and run Docker containers with Nginx
      if: env.USE_NGINX == 'true'
      run: |
        docker-compose -f docker-compose.nginx.yml up --build -d
